### PR TITLE
add Python3 compatibility

### PR DESCRIPTION
**Pull request by dmhowcroft**
Just ran `futurize` on the code. Updating to Python3 compatibility is necessary since Python2 reaches end of life at the end of this year. For now these changes should not break Python2 compatibility.

I have not been able to test the changes, because I can only test my limited use case.

Can you confirm that these changes:
* [ ] don't break Python2 usage; and
* [ ] work in Python3 for whatever tests you have?

I also deleted the version number in `setup.py`; I assume we will want to add one back in.

### CODE REVIEW

**Comment by martinpopel** [comment]
I don't plan to use PyTreex anymore (if needed, I have [Udapi](https://github.com/udapi/udapi-python)), so I don't care whether it uses Python 2 or 3. I leave it up to @tuetschek.

**Comment by dmhowcroft** [comment]
I see. The reason I did the updates was because I'd like to move @tuetschek's TGen to Python3 as well, but the way I'm using it it still depends on PyTreex.

**Comment by tuetschek** [comment]
Thanks @dmhowcroft ! The changes seem OK and it doesn't crash (the only test I have 😇). Actually the logs pointed out one minor bug to me (which never manifested in TGen and never will, it's in an old, abandoned code used for tecto-to-AMR conversions). 

I guess I should remove this dependency with the tree-based generation from TGen altogether (it doesn't work all that well anyway), but don't have time to maintain it at the moment 🙁.

**Comment by tuetschek** [comment]
Just out of curiosity, @dmhowcroft , why did you remove the version info? I agree it's pretty unnecessary, but was it breaking things?

**Comment by dmhowcroft** [comment]
Ah, I've been using Pipenv to manage my environments and got into some weird state when I started editing things and trying to load my modified version as a dependency. I don't think removing it helped.

I was using the semantic completeness reranker with a different NLG system recently, which required putting that output into Treex format (even just as a totally flat tree) in order to get TGen to run on it easily. That's why I've been fiddling with PyTreex at all.

**Comment by tuetschek** [comment]
Oops, I guess I never made this part work with plaintexts 😳... I only ever used the reranker stand-alone to debug it. Did you manage to make it run in the end?

**Comment by dmhowcroft** [comment]
Yeah, I just added Treex as a dependency, learnt enough Perl to install and configure it, and added this to my Makefile:

```Makefile    
%.e2e-text.yaml.tgz: %.e2e-text.txt
	treex -Len Read::Sentences from=$< W2A::Tokenize Write::YAML to=$@

%.e2e-text.completeness: %.e2e-das.txt %.e2e-text.yaml.tgz
	python2 $(TGEN_DIR)/run_tgen.py rerank_cl_eval $(TGEN_DIR)/$(CORPUS)/models/tftreecl.pickle.gz $^ > $@
```

**Comment by tuetschek** [comment]
@dmhowcroft : Nice 👍 !

**Pull request merged**
